name: Ryan's blog
description: Blogging about stuffs - useful and not useful
meta_description: "Ryan McKinnon personal experiment/blog | located in Wake Forest NC"

markdown: kramdown
highlighter: rouge
logo: false
baseurl: /
domain_name: http://ryanmckinnon.com
google_analytics: 'UA-20123430-2'
twitter_username: 'ryanmckinnon'
github_username: 'rdmckinnon'
linkedin_username: 'ryanmckinnon'
facebook_username: 'rdmckinnon'

# Details for the RSS feed generator
url:            'ryanmckinnon.com'
author:         'Ryan McKinnon'
